package com.component;

import com.event.EventMenuSelected;
import com.model.Model_Menu;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;


public class Menu extends javax.swing.JPanel {

   private EventMenuSelected event;
   
   public void addEventMenuSelected(EventMenuSelected event){
       this.event = event;
       listMenu2.addEventMenuSelected(event);
   }
   
    public Menu() {
        initComponents();
        setOpaque(false);
        listMenu2.setOpaque(false);
        init();
    }
    private void init(){
    listMenu2.addItem(new Model_Menu("1","Beranda",Model_Menu.MenuType.MENU));
    listMenu2.addItem(new Model_Menu("2","Kamar",Model_Menu.MenuType.MENU));
    listMenu2.addItem(new Model_Menu("3","Profi",Model_Menu.MenuType.MENU));
    listMenu2.addItem(new Model_Menu("4","Keuangan",Model_Menu.MenuType.MENU));
    listMenu2.addItem(new Model_Menu("5","transaksi",Model_Menu.MenuType.MENU));
    listMenu2.addItem(new Model_Menu("6","Laporan",Model_Menu.MenuType.MENU));
    listMenu2.addItem(new Model_Menu("","",Model_Menu.MenuType.EMPTY));
    listMenu2.addItem(new Model_Menu("","",Model_Menu.MenuType.EMPTY));
    listMenu2.addItem(new Model_Menu("7","Logout",Model_Menu.MenuType.MENU)); 
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMoving = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listMenu2 = new com.swing.ListMenu<>();

        PanelMoving.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/logo (100px).png"))); // NOI18N
        jLabel1.setText("Smart Kost");

        javax.swing.GroupLayout PanelMovingLayout = new javax.swing.GroupLayout(PanelMoving);
        PanelMoving.setLayout(PanelMovingLayout);
        PanelMovingLayout.setHorizontalGroup(
            PanelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMovingLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMovingLayout.setVerticalGroup(
            PanelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMovingLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listMenu2.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelMoving, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(listMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(PanelMoving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(listMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintChildren(Graphics grpchs) {
        super.paintChildren(grpchs); 
        Graphics2D g2=(Graphics2D)grpchs;
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g=new GradientPaint(0, 0, Color.decode("#F76B9F"), 0, getHeight(), Color.decode("#D94EBC"));
        g2.setPaint(g);
    g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
    g2.fillRect(getWidth() - 20, 0,getWidth(), getHeight());
    super.paintChildren(grpchs);
    }
private int x;
private int y;

public void initMoving(JFrame fram){
    PanelMoving.addMouseListener(new  MouseAdapter(){
        @Override
        public void mousePressed(MouseEvent me) {
           x = me.getX();
           y = me.getY();
        }
        
    });
    PanelMoving.addMouseMotionListener(new MouseMotionAdapter(){
        @Override
        public void mouseDragged(MouseEvent me) {
            fram.setLocation(me.getXOnScreen()-x, me.getYOnScreen()-y);
        }
       
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMoving;
    private javax.swing.JLabel jLabel1;
    private com.swing.ListMenu<String> listMenu2;
    // End of variables declaration//GEN-END:variables
}
